/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tachyon.core.views;

/**
 *
 * @author Aniket
 */
public class BootstrapTab extends SamplesTab {

    public BootstrapTab() {
        super("Bootstrap");
        add("Bootstrap Example", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<div class=\"container\">\n"
                + "  <div class=\"jumbotron\">\n"
                + "    <h1>My First Bootstrap Page</h1>\n"
                + "    <p>Resize this responsive page to see the effect!</p>\n"
                + "  </div>\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <h3>Column 1</h3>\n"
                + "      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>\n"
                + "      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <h3>Column 2</h3>\n"
                + "      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>\n"
                + "      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <h3>Column 3</h3>\n"
                + "      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>\n"
                + "      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Blog", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */\n"
                + "    .row.content {height: 1500px}\n"
                + "    \n"
                + "    /* Set gray background color and 100% height */\n"
                + "    .sidenav {\n"
                + "      background-color: #f1f1f1;\n"
                + "      height: 100%;\n"
                + "    }\n"
                + "    \n"
                + "    /* Set black background color, white text and some padding */\n"
                + "    footer {\n"
                + "      background-color: #555;\n"
                + "      color: white;\n"
                + "      padding: 15px;\n"
                + "    }\n"
                + "    \n"
                + "    /* On small screens, set height to 'auto' for sidenav and grid */\n"
                + "    @media screen and (max-width: 767px) {\n"
                + "      .sidenav {\n"
                + "        height: auto;\n"
                + "        padding: 15px;\n"
                + "      }\n"
                + "      .row.content {height: auto;}\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<div class=\"container-fluid\">\n"
                + "  <div class=\"row content\">\n"
                + "    <div class=\"col-sm-3 sidenav\">\n"
                + "      <h4>John's Blog</h4>\n"
                + "      <ul class=\"nav nav-pills nav-stacked\">\n"
                + "        <li class=\"active\"><a href=\"#section1\">Home</a></li>\n"
                + "        <li><a href=\"#section2\">Friends</a></li>\n"
                + "        <li><a href=\"#section3\">Family</a></li>\n"
                + "        <li><a href=\"#section3\">Photos</a></li>\n"
                + "      </ul><br>\n"
                + "      <div class=\"input-group\">\n"
                + "        <input type=\"text\" class=\"form-control\" placeholder=\"Search Blog..\">\n"
                + "        <span class=\"input-group-btn\">\n"
                + "          <button class=\"btn btn-default\" type=\"button\">\n"
                + "            <span class=\"glyphicon glyphicon-search\"></span>\n"
                + "          </button>\n"
                + "        </span>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <div class=\"col-sm-9\">\n"
                + "      <h4><small>RECENT POSTS</small></h4>\n"
                + "      <hr>\n"
                + "      <h2>I Love Food</h2>\n"
                + "      <h5><span class=\"glyphicon glyphicon-time\"></span> Post by Jane Dane, Sep 27, 2015.</h5>\n"
                + "      <h5><span class=\"label label-danger\">Food</span> <span class=\"label label-primary\">Ipsum</span></h5><br>\n"
                + "      <p>Food is my passion. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n"
                + "      <br><br>\n"
                + "      \n"
                + "      <h4><small>RECENT POSTS</small></h4>\n"
                + "      <hr>\n"
                + "      <h2>Officially Blogging</h2>\n"
                + "      <h5><span class=\"glyphicon glyphicon-time\"></span> Post by John Doe, Sep 24, 2015.</h5>\n"
                + "      <h5><span class=\"label label-success\">Lorem</span></h5><br>\n"
                + "      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n"
                + "      <hr>\n"
                + "\n"
                + "      <h4>Leave a Comment:</h4>\n"
                + "      <form role=\"form\">\n"
                + "        <div class=\"form-group\">\n"
                + "          <textarea class=\"form-control\" rows=\"3\" required></textarea>\n"
                + "        </div>\n"
                + "        <button type=\"submit\" class=\"btn btn-success\">Submit</button>\n"
                + "      </form>\n"
                + "      <br><br>\n"
                + "      \n"
                + "      <p><span class=\"badge\">2</span> Comments:</p><br>\n"
                + "      \n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-2 text-center\">\n"
                + "          <img src=\"bandmember.jpg\" class=\"img-circle\" height=\"65\" width=\"65\" alt=\"Avatar\">\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-10\">\n"
                + "          <h4>Anja <small>Sep 29, 2015, 9:12 PM</small></h4>\n"
                + "          <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n"
                + "          <br>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-2 text-center\">\n"
                + "          <img src=\"bird.jpg\" class=\"img-circle\" height=\"65\" width=\"65\" alt=\"Avatar\">\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-10\">\n"
                + "          <h4>John Row <small>Sep 25, 2015, 8:25 PM</small></h4>\n"
                + "          <p>I am so happy for you man! Finally. I am looking forward to read about your trendy life. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n"
                + "          <br>\n"
                + "          <p><span class=\"badge\">1</span> Comment:</p><br>\n"
                + "          <div class=\"row\">\n"
                + "            <div class=\"col-sm-2 text-center\">\n"
                + "              <img src=\"bird.jpg\" class=\"img-circle\" height=\"65\" width=\"65\" alt=\"Avatar\">\n"
                + "            </div>\n"
                + "            <div class=\"col-xs-10\">\n"
                + "              <h4>Nested Bro <small>Sep 25, 2015, 8:28 PM</small></h4>\n"
                + "              <p>Me too! WOW!</p>\n"
                + "              <br>\n"
                + "            </div>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<footer class=\"container-fluid\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Portfolio", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Remove the navbar's default margin-bottom and rounded borders */\n"
                + "    .navbar {\n"
                + "      margin-bottom: 0;\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "    \n"
                + "    /* Add a gray background color and some padding to the footer */\n"
                + "    footer {\n"
                + "      background-color: #f2f2f2;\n"
                + "      padding: 25px;\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Portfolio</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">About</a></li>\n"
                + "        <li><a href=\"#\">Gallery</a></li>\n"
                + "        <li><a href=\"#\">Contact</a></li>\n"
                + "      </ul>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "\n"
                + "<div class=\"jumbotron\">\n"
                + "  <div class=\"container text-center\">\n"
                + "    <h1>My Portfolio</h1>\n"
                + "    <p>Some text that represents \"Me\"...</p>\n"
                + "  </div>\n"
                + "</div>\n"
                + "  \n"
                + "<div class=\"container-fluid bg-3 text-center\">\n"
                + "  <h3>Some of my Work</h3><br>\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br>\n"
                + "\n"
                + "<div class=\"container-fluid bg-3 text-center\">\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <p>Some text..</p>\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br><br>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Webpage", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Remove the navbar's default margin-bottom and rounded borders */\n"
                + "    .navbar {\n"
                + "      margin-bottom: 0;\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "    \n"
                + "    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */\n"
                + "    .row.content {height: 450px}\n"
                + "    \n"
                + "    /* Set gray background color and 100% height */\n"
                + "    .sidenav {\n"
                + "      padding-top: 20px;\n"
                + "      background-color: #f1f1f1;\n"
                + "      height: 100%;\n"
                + "    }\n"
                + "    \n"
                + "    /* Set black background color, white text and some padding */\n"
                + "    footer {\n"
                + "      background-color: #555;\n"
                + "      color: white;\n"
                + "      padding: 15px;\n"
                + "    }\n"
                + "    \n"
                + "    /* On small screens, set height to 'auto' for sidenav and grid */\n"
                + "    @media screen and (max-width: 767px) {\n"
                + "      .sidenav {\n"
                + "        height: auto;\n"
                + "        padding: 15px;\n"
                + "      }\n"
                + "      .row.content {height:auto;}\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">About</a></li>\n"
                + "        <li><a href=\"#\">Projects</a></li>\n"
                + "        <li><a href=\"#\">Contact</a></li>\n"
                + "      </ul>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "  \n"
                + "<div class=\"container-fluid text-center\">\n"
                + "  <div class=\"row content\">\n"
                + "    <div class=\"col-sm-2 sidenav\">\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-8 text-left\">\n"
                + "      <h1>Welcome</h1>\n"
                + "      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n"
                + "      <hr>\n"
                + "      <h3>Test</h3>\n"
                + "      <p>Lorem ipsum...</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2 sidenav\">\n"
                + "      <div class=\"well\">\n"
                + "        <p>ADS</p>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "        <p>ADS</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Social", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Set black background color, white text and some padding */\n"
                + "    footer {\n"
                + "      background-color: #555;\n"
                + "      color: white;\n"
                + "      padding: 15px;\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">Messages</a></li>\n"
                + "      </ul>\n"
                + "      <form class=\"navbar-form navbar-right\" role=\"search\">\n"
                + "        <div class=\"form-group input-group\">\n"
                + "          <input type=\"text\" class=\"form-control\" placeholder=\"Search..\">\n"
                + "          <span class=\"input-group-btn\">\n"
                + "            <button class=\"btn btn-default\" type=\"button\">\n"
                + "              <span class=\"glyphicon glyphicon-search\"></span>\n"
                + "            </button>\n"
                + "          </span>\n"
                + "        </div>\n"
                + "      </form>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> My Account</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "  \n"
                + "<div class=\"container text-center\">\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-3 well\">\n"
                + "      <div class=\"well\">\n"
                + "        <p><a href=\"#\">My Profile</a></p>\n"
                + "        <img src=\"bird.jpg\" class=\"img-circle\" height=\"65\" width=\"65\" alt=\"Avatar\">\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "        <p><a href=\"#\">Interests</a></p>\n"
                + "        <p>\n"
                + "          <span class=\"label label-default\">News</span>\n"
                + "          <span class=\"label label-primary\">W3Schools</span>\n"
                + "          <span class=\"label label-success\">Labels</span>\n"
                + "          <span class=\"label label-info\">Football</span>\n"
                + "          <span class=\"label label-warning\">Gaming</span>\n"
                + "          <span class=\"label label-danger\">Friends</span>\n"
                + "        </p>\n"
                + "      </div>\n"
                + "      <div class=\"alert alert-success fade in\">\n"
                + "        <a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">×</a>\n"
                + "        <p><strong>Ey!</strong></p>\n"
                + "        People are looking at your profile. Find out who.\n"
                + "      </div>\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "      <p><a href=\"#\">Link</a></p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-7\">\n"
                + "    \n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-12\">\n"
                + "          <div class=\"panel panel-default text-left\">\n"
                + "            <div class=\"panel-body\">\n"
                + "              <p contenteditable=\"true\">Status: Feeling Blue</p>\n"
                + "              <button type=\"button\" class=\"btn btn-default btn-sm\">\n"
                + "                <span class=\"glyphicon glyphicon-thumbs-up\"></span> Like\n"
                + "              </button>\n"
                + "            </div>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      \n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "           <p>John</p>\n"
                + "           <img src=\"bird.jpg\" class=\"img-circle\" height=\"55\" width=\"55\" alt=\"Avatar\">\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-9\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "           <p>Bo</p>\n"
                + "           <img src=\"bandmember.jpg\" class=\"img-circle\" height=\"55\" width=\"55\" alt=\"Avatar\">\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-9\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "           <p>Jane</p>\n"
                + "           <img src=\"bandmember.jpg\" class=\"img-circle\" height=\"55\" width=\"55\" alt=\"Avatar\">\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-9\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "           <p>Anja</p>\n"
                + "           <img src=\"bird.jpg\" class=\"img-circle\" height=\"55\" width=\"55\" alt=\"Avatar\">\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-9\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2 well\">\n"
                + "      <div class=\"thumbnail\">\n"
                + "        <p>Upcoming Events:</p>\n"
                + "        <img src=\"paris.jpg\" alt=\"Paris\" width=\"400\" height=\"300\">\n"
                + "        <p><strong>Paris</strong></p>\n"
                + "        <p>Fri. 27 November 2015</p>\n"
                + "        <button class=\"btn btn-primary\">Info</button>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "        <p>ADS</p>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "        <p>ADS</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Marketing", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Remove the navbar's default margin-bottom and rounded borders */\n"
                + "    .navbar {\n"
                + "      margin-bottom: 0;\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "    \n"
                + "    /* Add a gray background color and some padding to the footer */\n"
                + "    footer {\n"
                + "      background-color: #f2f2f2;\n"
                + "      padding: 25px;\n"
                + "    }\n"
                + "    \n"
                + "  .carousel-inner img {\n"
                + "      width: 100%; /* Set width to 100% */\n"
                + "      margin: auto;\n"
                + "      min-height:200px;\n"
                + "  }\n"
                + "\n"
                + "  /* Hide the carousel text when the screen is less than 600 pixels wide */\n"
                + "  @media (max-width: 600px) {\n"
                + "    .carousel-caption {\n"
                + "      display: none;\n"
                + "    }\n"
                + "  }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">About</a></li>\n"
                + "        <li><a href=\"#\">Projects</a></li>\n"
                + "        <li><a href=\"#\">Contact</a></li>\n"
                + "      </ul>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "\n"
                + "<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n"
                + "    <!-- Indicators -->\n"
                + "    <ol class=\"carousel-indicators\">\n"
                + "      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n"
                + "      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n"
                + "    </ol>\n"
                + "\n"
                + "    <!-- Wrapper for slides -->\n"
                + "    <div class=\"carousel-inner\" role=\"listbox\">\n"
                + "      <div class=\"item active\">\n"
                + "        <img src=\"http://placehold.it/1200x400?text=IMAGE\" alt=\"Image\">\n"
                + "        <div class=\"carousel-caption\">\n"
                + "          <h3>Sell $</h3>\n"
                + "          <p>Money Money.</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "\n"
                + "      <div class=\"item\">\n"
                + "        <img src=\"http://placehold.it/1200x400?text=Another Image Maybe\" alt=\"Image\">\n"
                + "        <div class=\"carousel-caption\">\n"
                + "          <h3>More Sell $</h3>\n"
                + "          <p>Lorem ipsum...</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <!-- Left and right controls -->\n"
                + "    <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\n"
                + "      <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n"
                + "      <span class=\"sr-only\">Previous</span>\n"
                + "    </a>\n"
                + "    <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\n"
                + "      <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n"
                + "      <span class=\"sr-only\">Next</span>\n"
                + "    </a>\n"
                + "</div>\n"
                + "  \n"
                + "<div class=\"container text-center\">\n"
                + "  <h3>What We Do</h3><br>\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Current Project</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Project 2</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Marketing 2", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Add a gray background color and some padding to the footer */\n"
                + "    footer {\n"
                + "      background-color: #f2f2f2;\n"
                + "      padding: 25px;\n"
                + "    }\n"
                + "\n"
                + "    .carousel-inner img {\n"
                + "      width: 100%; /* Set width to 100% */\n"
                + "      min-height: 200px;\n"
                + "    }\n"
                + "\n"
                + "    /* Hide the carousel text when the screen is less than 600 pixels wide */\n"
                + "    @media (max-width: 600px) {\n"
                + "      .carousel-caption {\n"
                + "        display: none;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">About</a></li>\n"
                + "        <li><a href=\"#\">Projects</a></li>\n"
                + "        <li><a href=\"#\">Contact</a></li>\n"
                + "      </ul>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "\n"
                + "<div class=\"container\">\n"
                + "<div class=\"row\">\n"
                + "  <div class=\"col-sm-8\">\n"
                + "    <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n"
                + "      <!-- Indicators -->\n"
                + "      <ol class=\"carousel-indicators\">\n"
                + "        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n"
                + "        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n"
                + "      </ol>\n"
                + "\n"
                + "      <!-- Wrapper for slides -->\n"
                + "      <div class=\"carousel-inner\" role=\"listbox\">\n"
                + "        <div class=\"item active\">\n"
                + "          <img src=\"http://placehold.it/800x400?text=IMAGE\" alt=\"Image\">\n"
                + "          <div class=\"carousel-caption\">\n"
                + "            <h3>Sell $</h3>\n"
                + "            <p>Money Money.</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "\n"
                + "        <div class=\"item\">\n"
                + "          <img src=\"http://placehold.it/800x400?text=Another Image Maybe\" alt=\"Image\">\n"
                + "          <div class=\"carousel-caption\">\n"
                + "            <h3>More Sell $</h3>\n"
                + "            <p>Lorem ipsum...</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "\n"
                + "      <!-- Left and right controls -->\n"
                + "      <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\n"
                + "        <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n"
                + "        <span class=\"sr-only\">Previous</span>\n"
                + "      </a>\n"
                + "      <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\n"
                + "        <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n"
                + "        <span class=\"sr-only\">Next</span>\n"
                + "      </a>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "  <div class=\"col-sm-4\">\n"
                + "    <div class=\"well\">\n"
                + "      <p>Some text..</p>\n"
                + "    </div>\n"
                + "    <div class=\"well\">\n"
                + "       <p>Upcoming Events..</p>\n"
                + "    </div>\n"
                + "    <div class=\"well\">\n"
                + "       <p>Visit Our Blog</p>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "<hr>\n"
                + "</div>\n"
                + "\n"
                + "<div class=\"container text-center\">\n"
                + "  <h3>What We Do</h3>\n"
                + "  <br>\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Current Project</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Project 2</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-3\">\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "      <div class=\"well\">\n"
                + "       <p>Some text..</p>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "  <hr>\n"
                + "</div>\n"
                + "\n"
                + "<div class=\"container text-center\">\n"
                + "  <h3>Our Partners</h3>\n"
                + "  <br>\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 1</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 2</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 3</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 4</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 5</p>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-2\">\n"
                + "      <img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\">\n"
                + "      <p>Partner 6</p>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Footer Text</p>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Analytics", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */\n"
                + "    .row.content {height: 550px}\n"
                + "    \n"
                + "    /* Set gray background color and 100% height */\n"
                + "    .sidenav {\n"
                + "      background-color: #f1f1f1;\n"
                + "      height: 100%;\n"
                + "    }\n"
                + "        \n"
                + "    /* On small screens, set height to 'auto' for the grid */\n"
                + "    @media screen and (max-width: 767px) {\n"
                + "      .row.content {height: auto;}\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse visible-xs\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Dashboard</a></li>\n"
                + "        <li><a href=\"#\">Age</a></li>\n"
                + "        <li><a href=\"#\">Gender</a></li>\n"
                + "        <li><a href=\"#\">Geo</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "\n"
                + "<div class=\"container-fluid\">\n"
                + "  <div class=\"row content\">\n"
                + "    <div class=\"col-sm-3 sidenav hidden-xs\">\n"
                + "      <h2>Logo</h2>\n"
                + "      <ul class=\"nav nav-pills nav-stacked\">\n"
                + "        <li class=\"active\"><a href=\"#section1\">Dashboard</a></li>\n"
                + "        <li><a href=\"#section2\">Age</a></li>\n"
                + "        <li><a href=\"#section3\">Gender</a></li>\n"
                + "        <li><a href=\"#section3\">Geo</a></li>\n"
                + "      </ul><br>\n"
                + "    </div>\n"
                + "    <br>\n"
                + "    \n"
                + "    <div class=\"col-sm-9\">\n"
                + "      <div class=\"well\">\n"
                + "        <h4>Dashboard</h4>\n"
                + "        <p>Some text..</p>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "            <h4>Users</h4>\n"
                + "            <p>1 Million</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "            <h4>Pages</h4>\n"
                + "            <p>100 Million</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "            <h4>Sessions</h4>\n"
                + "            <p>10 Million</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-3\">\n"
                + "          <div class=\"well\">\n"
                + "            <h4>Bounce</h4>\n"
                + "            <p>30%</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-4\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-4\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-4\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "            <p>Text</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"row\">\n"
                + "        <div class=\"col-sm-8\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Text</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "        <div class=\"col-sm-4\">\n"
                + "          <div class=\"well\">\n"
                + "            <p>Text</p>\n"
                + "          </div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Online Store", "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <title>Bootstrap Example</title>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n"
                + "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                + "  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"
                + "  <style>\n"
                + "    /* Remove the navbar's default rounded borders and increase the bottom margin */\n"
                + "    .navbar {\n"
                + "      margin-bottom: 50px;\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "    \n"
                + "    /* Remove the jumbotron's default bottom margin */\n"
                + "     .jumbotron {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "   \n"
                + "    /* Add a gray background color and some padding to the footer */\n"
                + "    footer {\n"
                + "      background-color: #f2f2f2;\n"
                + "      padding: 25px;\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<div class=\"jumbotron\">\n"
                + "  <div class=\"container text-center\">\n"
                + "    <h1>Online Store</h1>\n"
                + "    <p>Mission, Vission & Values</p>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<nav class=\"navbar navbar-inverse\">\n"
                + "  <div class=\"container-fluid\">\n"
                + "    <div class=\"navbar-header\">\n"
                + "      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "        <span class=\"icon-bar\"></span>\n"
                + "      </button>\n"
                + "      <a class=\"navbar-brand\" href=\"#\">Logo</a>\n"
                + "    </div>\n"
                + "    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n"
                + "      <ul class=\"nav navbar-nav\">\n"
                + "        <li class=\"active\"><a href=\"#\">Home</a></li>\n"
                + "        <li><a href=\"#\">Products</a></li>\n"
                + "        <li><a href=\"#\">Deals</a></li>\n"
                + "        <li><a href=\"#\">Stores</a></li>\n"
                + "        <li><a href=\"#\">Contact</a></li>\n"
                + "      </ul>\n"
                + "      <ul class=\"nav navbar-nav navbar-right\">\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> Your Account</a></li>\n"
                + "        <li><a href=\"#\"><span class=\"glyphicon glyphicon-shopping-cart\"></span> Cart</a></li>\n"
                + "      </ul>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</nav>\n"
                + "\n"
                + "<div class=\"container\">\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-primary\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-danger\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-success\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br>\n"
                + "\n"
                + "<div class=\"container\">\n"
                + "  <div class=\"row\">\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-primary\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-primary\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <div class=\"col-sm-4\">\n"
                + "      <div class=\"panel panel-primary\">\n"
                + "        <div class=\"panel-heading\">BLACK FRIDAY DEAL</div>\n"
                + "        <div class=\"panel-body\"><img src=\"http://placehold.it/150x80?text=IMAGE\" class=\"img-responsive\" style=\"width:100%\" alt=\"Image\"></div>\n"
                + "        <div class=\"panel-footer\">Buy 50 mobiles and get a gift card</div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div><br><br>\n"
                + "\n"
                + "<footer class=\"container-fluid text-center\">\n"
                + "  <p>Online Store Copyright</p>\n"
                + "  <form class=\"form-inline\">Get deals:\n"
                + "    <input type=\"email\" class=\"form-control\" size=\"50\" placeholder=\"Email Address\">\n"
                + "    <button type=\"button\" class=\"btn btn-danger\">Sign Up</button>\n"
                + "  </form>\n"
                + "</footer>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
    }
}
