/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tachyon.core.views;

/**
 *
 * @author Aniket
 */
public class HTMLTab extends SamplesTab {

    public HTMLTab() {
        super("HTML");
        add("HTML Document", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>My First Heading</h1>\n"
                + "\n"
                + "<p>My first paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Headings", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>This is heading 1</h1>\n"
                + "<h2>This is heading 2</h2>\n"
                + "<h3>This is heading 3</h3>\n"
                + "<h4>This is heading 4</h4>\n"
                + "<h5>This is heading 5</h5>\n"
                + "<h6>This is heading 6</h6>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Paragraphs", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>This is a paragraph.</p>\n"
                + "<p>This is a paragraph.</p>\n"
                + "<p>This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Links", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<a href=\"http://gluonhq.com\">This is a link</a>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Images", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<img src=\"http://gluonhq.com/wp-content/uploads/2015/02/Gluon_Reverse_Blue2-1024x305.png\" alt=\"Gluon logo\" width=\"104\" height=\"142\">\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Title Attribute", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>About W3Schools</h1>\n"
                + "\n"
                + "<p title=\"About W3Schools\">\n"
                + "W3Schools is a web developer's site.\n"
                + "It provides tutorials and references covering\n"
                + "many aspects of web programming,\n"
                + "including HTML, CSS, JavaScript, XML, SQL, PHP, ASP, etc.\n"
                + "</p>\n"
                + "\n"
                + "<p><b>\n"
                + "If you move the mouse over the paragraph above,\n"
                + "the title will display as a tooltip.\n"
                + "</b></p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Href Attribute", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<a href=\"http://www.gluonhq.com\">This is a link</a>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Width and Height Properties", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<img src=\"w3schools.jpg\" width=\"104\" height=\"142\">\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Alt Attribute", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<img src=\"w3schools.jpg\" alt=\"W3Schools.com\" width=\"104\" height=\"142\">\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Attribute without quotes", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<a href=http://www.w3schools.com>This is a link</a>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Attribute without quotes does not work", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>About W3Schools</h1>\n"
                + "\n"
                + "<p title=About W3Schools>\n"
                + "You cannot omit quotes around an attribute value\n"
                + "if the value contains spaces.\n"
                + "</p>\n"
                + "\n"
                + "<p><b>\n"
                + "If you move the mouse over the paragraph above,\n"
                + "your browser will only display the first word from the title.\n"
                + "</b></p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Headings", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>This is heading 1</h1>\n"
                + "<h2>This is heading 2</h2>\n"
                + "<h3>This is heading 3</h3>\n"
                + "<h4>This is heading 4</h4>\n"
                + "<h5>This is heading 5</h5>\n"
                + "<h6>This is heading 6</h6>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Horizontal Rules", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>The hr tag defines a horizontal rule:</p>\n"
                + "<hr>\n"
                + "<p>This is a paragraph.</p>\n"
                + "<hr>\n"
                + "<p>This is a paragraph.</p>\n"
                + "<hr>\n"
                + "<p>This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML head", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "  <title>My First HTML</title>\n"
                + "  <meta charset=\"UTF-8\">\n"
                + "</head>\n"
                + "<body>\n"
                + "\n"
                + "<p>The HTML head element contains meta data.</p>\n"
                + "<p>Meta data is data about the HTML document.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Paragraphs", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>This is a paragraph.</p>\n"
                + "<p>This is a paragraph.</p>\n"
                + "<p>This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>");
        add("Line breaks in HTML", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>This is<br>a para<br>graph with line breaks</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("HTML Formatting problems", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>In HTML, spaces and new lines are ignored:</p>\n"
                + "\n"
                + "<p>\n"
                + "\n"
                + "  My Bonnie lies over the ocean.\n"
                + "\n"
                + "  My Bonnie lies over the sea.\n"
                + "\n"
                + "  My Bonnie lies over the ocean.\n"
                + "  \n"
                + "  Oh, bring back my Bonnie to me.\n"
                + "\n"
                + "</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Controlling line breaks and spaces", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<p>The pre tag preserves both spaces and line breaks:</p>\n"
                + "\n"
                + "<pre>\n"
                + "   My Bonnie lies over the ocean.\n"
                + "\n"
                + "   My Bonnie lies over the sea.\n"
                + "\n"
                + "   My Bonnie lies over the ocean.\n"
                + "   \n"
                + "   Oh, bring back my Bonnie to me.\n"
                + "</pre>\n"
                + "\n"
                + "</body>\n"
                + "</html>");
        add("Styles", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h2 style=\"color:red;\">I am red</h2>\n"
                + "<h2 style=\"color:blue;\">I am blue</h2>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Background Color", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body style=\"background-color:lightgrey;\">\n"
                + "\n"
                + "<h1>This is a heading</h1>\n"
                + "<p>This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Text Color", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1 style=\"color:blue;\">This is a heading</h1>\n"
                + "<p style=\"color:red;\">This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Text Font", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1 style=\"font-family:verdana;\">This is a heading</h1>\n"
                + "<p style=\"font-family:courier;\">This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Text Size", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1 style=\"font-size:300%;\">This is a heading</h1>\n"
                + "<p style=\"font-size:160%;\">This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Text Alignment", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1 style=\"text-align:center;\">Centered heading</h1>\n"
                + "<p>This is a paragraph.</p>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
    }

}
