/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tachyon.core.views;

/**
 *
 * @author Aniket
 */
public class JavaScriptTab extends SamplesTab {

    public JavaScriptTab() {
        super("JavaScript");
        add("Change HTML Content", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>What Can JavaScript Do?</h1>\n"
                + "\n"
                + "<p id=\"demo\">JavaScript can change HTML content.</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"document.getElementById('demo').innerHTML = 'Hello JavaScript!'\">Click Me!</button>\n"
                + "\n"
                + "</body>\n"
                + "</html>");
        add("Change HTML Attributes", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>What Can JavaScript Do?</h1>\n"
                + "\n"
                + "<p>JavaScript can change HTML attributes.</p>\n"
                + "\n"
                + "<p>In this case JavaScript changes the src (source) attribute of an image.</p>\n"
                + "\n"
                + "<button onclick=\"document.getElementById('myImage').src='http://www.w3schools.com/js/pic_bulbon.gif'\">Turn on the light</button>\n"
                + "\n"
                + "<img id=\"myImage\" src=\"http://www.w3schools.com/js/pic_bulboff.gif\" style=\"width:100px\">\n"
                + "\n"
                + "<button onclick=\"document.getElementById('myImage').src='http://www.w3schools.com/js/pic_bulboff.gif'\">Turn off the light</button>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Change CSS Style", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>What Can JavaScript Do?</h1>\n"
                + "\n"
                + "<p id=\"demo\">JavaScript can change the style of an HTML element.</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"document.getElementById('demo').style.fontSize='35px'\">Click Me!</button>\n"
                + "\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Hide HTML Elements", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>What Can JavaScript Do?</h1>\n"
                + "\n"
                + "<p id=\"demo\">JavaScript can hide HTML elements.</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"document.getElementById('demo').style.display='none'\">Click Me!</button>\n"
                + "\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Show Hidden HTML Elements", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>What Can JavaScript Do?</h1>\n"
                + "\n"
                + "<p>JavaScript can show hidden HTML elements.</p>\n"
                + "\n"
                + "<p id=\"demo\" style=\"display:none\">Hello JavaScript!</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"document.getElementById('demo').style.display='block'\">Click Me!</button>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Window Alert", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>My First Web Page</h1>\n"
                + "<p>My first paragraph.</p>\n"
                + "\n"
                + "<script>\n"
                + "window.alert(5 + 6);\n"
                + "</script>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Writing into HTML output", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>My First Web Page</h1>\n"
                + "<p>My first paragraph.</p>\n"
                + "\n"
                + "<script>\n"
                + "document.write(5 + 6);\n"
                + "</script>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("Writing into an HTML element", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>My First Web Page</h1>\n"
                + "<p>My First Paragraph.</p>\n"
                + "\n"
                + "<p id=\"demo\"></p>\n"
                + "\n"
                + "<script>\n"
                + "document.getElementById(\"demo\").innerHTML = 5 + 6;\n"
                + "</script>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("JavaScript in <head>", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "<script>\n"
                + "function myFunction() {\n"
                + "    document.getElementById(\"demo\").innerHTML = \"Paragraph changed.\";\n"
                + "}\n"
                + "</script>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "\n"
                + "<h1>JavaScript in Head</h1>\n"
                + "\n"
                + "<p id=\"demo\">A Paragraph.</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"myFunction()\">Try it</button>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
        add("JavaScript in <body>", "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<body>\n"
                + "\n"
                + "<h1>JavaScript in Body</h1>\n"
                + "\n"
                + "<p id=\"demo\">A Paragraph.</p>\n"
                + "\n"
                + "<button type=\"button\" onclick=\"myFunction()\">Try it</button>\n"
                + "\n"
                + "<script>\n"
                + "function myFunction() {\n"
                + "    document.getElementById(\"demo\").innerHTML = \"Paragraph changed.\";\n"
                + "}\n"
                + "</script>\n"
                + "\n"
                + "</body>\n"
                + "</html>\n"
                + "");
    }

}
